Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace ShoppingCart.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly ILogger<PaymentController> _logger;
        public PaymentController(ILogger<PaymentController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index(double total)
        {
            ViewData["Total"] = total;
            return View();
        }
        [HttpPost]
        public IActionResult Payment()
        {
            return RedirectToAction("PlaceOrder", "Cart");
        }
    }
}

Views/Payment/Index.cshtml
@section Title {
    <a class="navbar-brand" href="#">Payment</a>
}

@section NavbarText {
    <a class="nav-link text-dark">Total: $@ViewData["Total"]</a>
}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-lg-8 mx-auto text-center">
            <h1 class="display-4">Payment</h1>
        </div>
    </div> <!-- End -->
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card ">
                <div class="card-header">
                    <div class="bg-white shadow-sm pt-4 pl-2 pr-2 pb-2">
                        <!-- Credit card form tabs -->
                        <ul role="tablist" class="nav bg-light nav-pills rounded nav-fill mb-3">
                            <li class="nav-item"> 
                                <a data-toggle="pill" href="#credit-card" class="nav-link active "> 
                                    <i class="fas fa-credit-card mr-2"></i> Credit Card 
                                </a> 
                            </li>
                            <li class="nav-item"> 
                                <a data-toggle="pill" href="#paypal" class="nav-link "> 
                                    <i class="fab fa-paypal mr-2"></i> Paypal 
                                </a> 
                            </li>
                            <li class="nav-item"> 
                                <a data-toggle="pill" href="#net-banking" class="nav-link "> 
                                    <i class="fas fa-mobile-alt mr-2"></i> Net Banking 
                                </a> 
                            </li>
                        </ul>
                    </div> <!-- End -->
                    <!-- Credit card form content -->
                    <div class="tab-content">
                        <!-- credit card info-->
                        <div id="credit-card" class="tab-pane fade show active pt-3">
                            <div role="form">
                                <div class="form-group"> 
                                    <label for="username">
                                        <h6>Card Owner</h6>
                                    </label> 
                                    <input type="text" name="username" placeholder="Card Owner Name"  class="form-control "> 
                                </div>
                                <div class="form-group"> 
                                    <label for="cardNumber">
                                        <h6>Card number</h6>
                                    </label>
                                    <div class="input-group"> 
                                        <input type="text" name="cardNumber" placeholder="Valid card number" class="form-control " >
                                        <div class="input-group-append"> 
                                            <span class="input-group-text text-muted"> 
                                                <i class="fab fa-cc-visa mx-1"></i> 
                                                <i class="fab fa-cc-mastercard mx-1"></i> 
                                                <i class="fab fa-cc-amex mx-1"></i> 
                                            </span> 
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-8">
                                        <div class="form-group"> 
                                            <label>
                                                <span class="hidden-xs">
                                                    <h6>Expiration Date</h6>
                                                </span>
                                            </label>
                                            <div class="input-group"> 
                                                <input type="number" placeholder="MM" name="" class="form-control" > 
                                                <input type="number" placeholder="YY" name="" class="form-control" > 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group mb-4"> 
                                            <label data-toggle="tooltip" title="Three digit CV code on the back of your card">
                                                <h6>CVV <i class="fa fa-question-circle d-inline"></i></h6>
                                            </label> 
                                            <input type="text"  class="form-control"> 
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer"> 
                                    <form method="POST" asp-controller="Payment" asp-action="Payment">
                                        <button class="subscribe btn btn-primary btn-block shadow-sm" asp-controller="Payment" asp-action="Payment"> Confirm Payment </button>
                                    </form>
                            </div>
                        </div>
                    </div> <!-- End -->
                    <!-- Paypal info -->
                    <div id="paypal" class="tab-pane fade pt-3">
                        <h6 class="pb-2">Select your paypal account type</h6>
                        <div class="form-group "> 
                            <label class="radio-inline"> <input type="radio" name="optradio" checked> Domestic </label> 
                            <label class="radio-inline"> <input type="radio" name="optradio" class="ml-5">International </label>
                        </div>
                        <form method="POST" asp-controller="Payment" asp-action="Payment">
                            <p>        
                                <button class="btn btn-primary">
                                    <i class="fab fa-paypal mr-2"></i> Log into my Paypal
                                </button> 
                            </p>
                        </form>
                        <p class="text-muted"> Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your order. </p>
                    </div> <!-- End -->
                    <!-- bank transfer info -->
                    <div id="net-banking" class="tab-pane fade pt-3">
                        <div class="form-group "> 
                            <label for="Select Your Bank">
                                <h6>Select your Bank</h6>
                            </label> 
                            <select class="form-control" id="ccmonth">
                                <option value="" selected disabled>--Please select your Bank--</option>
                                <option>DBS</option>
                                <option>POSB</option>
                                <option>OCBC</option>
                                <option>UOB</option>
                            </select> </div>
                        <div class="form-group">
                            <form method="POST" asp-controller="Payment" asp-action="Payment">
                                <p> 
                                    <button class="btn btn-primary">
                                        <i class="fas fa-mobile-alt mr-2"></i> Proceed Pyment
                                    </button>
                                </p>
                            </form>
                        </div>
                        <p class="text-muted">Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your order. </p>
                    </div> <!-- End -->
                    <!-- End -->
                </div>
            </div>
        </div>
    </div>
</div>