Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.Extensions.Logging;
using ShoppingCart.Models;
using ShoppingCart.Database;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;

namespace ShoppingCart.Controllers
{
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> _logger;
        private ShoppingCartContext _dbContext;
        private AuthHash _authHash;
        public AuthController(ILogger<AuthController> logger, ShoppingCartContext dbContext, AuthHash authHash)
        {
            _logger = logger;
            _dbContext = dbContext;
            _authHash = authHash;
        }

        public IActionResult Index()
        {
            if (HttpContext.User.Claims.FirstOrDefault() != null)
                return RedirectToAction("Index", "Product");
            else
                return View();
        }

        [HttpPost]
        public async Task<string> Login(string userName, string password, [FromBody]List<CartDetail> cartDetails)
        {
            password = _authHash.GetHash(password);
            bool isRegistered = _dbContext.Users.Where(user => user.UserId == userName && user.Password == password).Any();
            if (isRegistered == true)
            {
                var claims = new List<Claim>{
                    new Claim(ClaimTypes.Name,userName)
                };
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);
                var props = new AuthenticationProperties();
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props);
                bool isMerged = MergeGuestCart(userName, cartDetails);
                if (isMerged)
                    return "/Cart/Index";
                else
                    return "/Product/Index";
            }
            else
                return "/Auth/Index";
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Product");
        }

        [Authorize]
        public bool MergeGuestCart(string userId, List<CartDetail> cartDetails)
        {
            var userCart = _dbContext.Carts.Where(c => c.UserId == userId).FirstOrDefault();
            if (cartDetails != null && cartDetails.Count() != 0)
            {
                if (userCart != null)
                {
                    foreach (var guestCartDetail in cartDetails)
                    {
                        var product = _dbContext.Products.Where(p => p.ProductId == guestCartDetail.ProductId).FirstOrDefault();
                        var userCartDetail = userCart.CartDetails.Where(cd => cd.ProductId == guestCartDetail.ProductId).FirstOrDefault();
                        if (product != null && guestCartDetail.Qty >= 0)
                        {
                            if (userCartDetail != null)
                            {
                                userCartDetail.Qty += guestCartDetail.Qty;
                            }
                            else
                            {
                                userCart.CartDetails.Add(new CartDetail()
                                {
                                    CartId = userCart.CartId,
                                    ProductId = guestCartDetail.ProductId,
                                    Qty = guestCartDetail.Qty,
                                    Product = product
                                });
                            }
                        }
                    }
                    userCart.Total = userCart.CartDetails.Sum(cd => cd.Qty * cd.Product.Price);
                    _dbContext.Carts.Update(userCart);
                }
                else
                {
                    // create user cart
                    userCart = new Cart()
                    {
                        UserId = userId,
                        CartId = Guid.NewGuid().ToString(),
                        Total = 0,
                        CartDetails = new List<CartDetail>()
                    };
                    foreach (var guestCartDetail in cartDetails)
                    {
                        var product = _dbContext.Products.Where(p => p.ProductId == guestCartDetail.ProductId).FirstOrDefault();
                        var qty = guestCartDetail.Qty;
                        if (product != null && qty >= 0)
                        {
                            userCart.CartDetails.Add(
                                new CartDetail
                                {
                                    CartId = userCart.CartId,
                                    ProductId = product.ProductId,
                                    Qty = qty,
                                    Product = product
                                });
                        }
                    }
                    userCart.Total = userCart.CartDetails.Sum(cd => cd.Qty * cd.Product.Price);
                    _dbContext.Carts.Add(userCart);
                }
                _dbContext.SaveChanges();
                return true;
            }
            return false;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.Extensions.Logging;
using ShoppingCart.Models;
using ShoppingCart.Database;
using Microsoft.AspNetCore.Authorization;

namespace ShoppingCart.Controllers
{
    [Authorize]
    public class PurchaseController : Controller
    {
        private readonly ILogger<PurchaseController> _logger;
        private ShoppingCartContext _dbContext;
        public PurchaseController(ILogger<PurchaseController> logger, ShoppingCartContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        // TODO: display purchases
        // send purchases and activation code to view
        public IActionResult Index(string name)
        {
            var userId = HttpContext.User.Claims.First().Value;
            List<Order> orders = _dbContext.Orders.Where(o => o.UserId == userId).OrderByDescending(o => o.UtcDateTime).ToList();
            return View(orders);
        }
    }
}

Views/Purchase/Index.cshtml
@model List<ShoppingCart.Models.Order>
@using System;
@{
    Layout= "~/Views/Shared/_Layout.cshtml";
}

@section Title {
    <a class="navbar-brand" href="#">My Purchases</a>
}

@section NavLink1 {
    <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Home</a>
}

@section NavLink2 {
    <form method="POST" asp-controller="Auth" asp-action="Logout">
        <button class="btn text-dark shadow-none" >Logout</button>
    </form>
}

@functions {
    string formatDateTime(DateTime dateTime)
    {
        return dateTime.ToLocalTime().ToString("d MMM yyyy - HH : mm");
    }
}

@if (Model.Count() == 0) 
{
    <h1 class="mt-4">Sorry, your purchase history is empty.</h1>
}
else 
{
    <div class="container">
        @foreach (var order in Model)
        {
            @foreach (var orderDetail in order.OrderDetails)
            {
                <div class="row mt-4 border border-secondary rounded bg-light pl-4">
                    <div class="col-5 h-100 my-auto">
                        <div class="row">
                            <div class="bg-transparent h-100 col-4 py-3">
                                <img src="~/img/@orderDetail.Product.Image" class="card-img-top h-100"/>
                            </div>
                            <div class="card-body h-30 col-8">
                                @* <div class="h-30"> *@
                                    <h5>@orderDetail.Product.Name</h5>
                                    <p class="card-text mb-0 overflow-hidden w-75 text-left pr-2">@orderDetail.Product.Description</p>
                                @* </div> *@
                            </div>
                        </div>
                    </div>
                    <div class="col-7">
                        <div class="container h-100 pl-5 py-2">
                            <div class="col align-middle d-inline">
                                <div class="row">
                                    <div class="col-4">
                                        <h5>Purchased On: </h5>
                                    </div>
                                    <div class="col-8">
                                        <p>@formatDateTime(order.UtcDateTime)</p>
                                    </div> 
                                </div>
                                <div class="row">
                                    <div class="col-4">
                                        <h5>Quantity: </h5>
                                    </div>
                                    <div class="col-8">
                                        <p>@orderDetail.Qty</p>
                                    </div> 
                                </div>
                                <div class="row">
                                    <div class="col-4">
                                        <h5>Activation Code: </h5>
                                    </div>
                                    <div class="col-8">
                                        <div class="row">
                                            <div class="dropdown col-6">
                                                <button class="btn btn-sm btn-info dropdown-toggle w-100" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Code List
                                                </button>
                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                    @for (int i = 0; i < orderDetail.Activations.Count(); i++)
                                                    {
                                                        <span class="dropdown-item codeItem" data-clipboard-text=@orderDetail.Activations.ElementAt(i).Code>@orderDetail.Activations.ElementAt(i).Code</span>
                                                    }
                                                </div>
                                            </div>
                                            <div class="col-6">
                                                <a class="btn btn-sm btn-info w-100" href="~/file/ASP.NET Core in Action.pdf" download="ASP.NET Core in Action.pdf">Download</a>
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
}
@section Scripts{
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="~/lib/clipboard/dist/clipboard.min.js"></script>
    <script>
        var codeItem = document.getElementsByClassName('codeItem');
        var clipboard = new ClipboardJS(codeItem);
        clipboard.on('success', function(e) {
            bootbox.alert("Copied to clipboard!!!");
        });
    </script>
}